# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeyaab', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
