# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_comment'),
        ('cafeyaab', '0006_user_fav_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fav_list',
        ),
        migrations.AddField(
            model_name='user',
            name='fav_list',
            field=models.ManyToManyField(default=None, to='cafe.Cafe'),
        ),
    ]
