# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cafe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.Cafe'),
        ),
    ]
