# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
