# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_auto_20171102_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
