# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 14:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cafe', '0004_comment_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='main_image_url',
            field=models.URLField(default='300.png'),
        ),
    ]
