# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_auto_20171102_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
