# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_cafe_popularity'),
        ('cafe', '0006_cafe_activated'),
    ]

    operations = [
    ]
