# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_merge_20171103_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='main_image_url',
            field=models.URLField(),
        ),
    ]
